apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: sample-app

sepc:
  replicas: 1
  selector:
    matchLabels:
      service: webapp
  template:
    metadata:
      labels:
        app: sample-app
        service: webapp
    spec:
      containers:
      - name: webapp
        image: acrmtiprecipe.azurecr.io/webapp:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80  
          protocol: TCP
        env:
          - name: ASPNETCORE_URLS
            value: http://+:80
          - name: WebApiBaseAddress
            value: http://webapi
