apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: sample-app
    service: webapp
spec:
   type: LoadBalancer
   ports:
   - port: 80
     targetPort: 80
     protocol: TCP
   selector:
     service: webapp 